### ISSUE TITLE
where is the mish_cpp?

### ISSUE THREAD

**Issue by hhl0202** [CoinCheung/pytorch-loss#13]
when i found mish.py ,i see MishV3,but we need "import mish_cpp",can i ask where is the mish_cpp?

**Comment by CoinCheung** [comment]
Hi,

You need to compile the source with command `python setup.py install`, then there will be some `.so` file generated, the `.so` file is the `mish_cpp`.

**Comment by CoinCheung** [comment]
you can find it out like this:
```
python
>>> import mish_cpp
>>> mish_cpp.__file__
```

**Comment by CoinCheung** [comment]
Closing this since you might have figured it out.
