### ISSUE TITLE
need cuda for installing on MacOs

### ISSUE THREAD

**Issue by reymondzzzz** [CoinCheung/pytorch-loss#14]
Can you fix setup.py for installing for cpu version MacOS?

**Comment by CoinCheung** [comment]
Hi,

Currently these code is only tested on linux (which is my working environment). I am afraid I cannot transfer the cuda code to mac OS in short future, but if you do not want to use cuda based code, you can copy-and-paste the pure pytorch codes to your project. It is easy to find it out by using `grep` command, please have try :)
