### ISSUE TITLE
Any plan to give a tutorial?

### ISSUE THREAD

**Issue by sean-zhuh** [CoinCheung/pytorch-loss#15]
Hi, it's a great work! However, I often found myself stuck on how to write a custom cuda kernel / C++ extension, do you have any plan to write a tutorial or generously give some helpful links? I found most tutorials on internet including PyTorch's official document on custom cuda kernel is not that welcome to new beginners.

**Comment by CoinCheung** [comment]
Writing tutorals about extend pytorch with cuda is beyond the scope of this repository, and, to be honest, it is also not in my todo list. But you can provide information about the problems you met here and let's see how we could make your extensions work.
