### ISSUE TITLE
LovaszSoftmax Loss test case not working

### ISSUE THREAD

**Issue by omerferhatt** [CoinCheung/pytorch-loss#21]
When I try to run your test case to check it out. It throws error.
```
terminate called after throwing an instance of 'thrust::system::system_error'
  what():  CUDA free failed: cudaErrorIllegalAddress: an illegal memory access was encountered
```

I'm using Python 3.7.10 and PyTorch 1.8.1. GPU is Nvidia RTX 3070.

**Comment by CoinCheung** [comment]
Hi,

I do not have experience with 3070 or cuda 11. Can your pytorch work well with pytorch native ops ? This problem can also be caused by numeric stablillity, would you please try with smaller lr or less regularization ?

**Comment by omerferhatt** [comment]
Yes, pytorch is working fine with the all other stuffs. It seems LovaszSoftmaxV1 working okay with both forward and backward but when I try to execute forward pass on V3 it gives the same error. And I changed lr and loss reg. too.

**Comment by CoinCheung** [comment]
It is a conflict problem of pytorch, you can install nighly-version of pytorch and see if there is still this problem. see this: https://github.com/pytorch/pytorch/issues/52663

**Comment by omerferhatt** [comment]
It's working with pytorch 1.9.0 cu11.1
