### ISSUE TITLE
there is some problems in the file of focal_loss.py

### ISSUE THREAD

**Issue by OliviaDdy** [CoinCheung/pytorch-loss#22]
in the file of focal_loss.py, how to import focal_cpp? I do not find  the file of focal_cpp.
And if my torch version is less than 1.6.0,how do I  apply?

**Comment by CoinCheung** [comment]
Hi,

by running the script: `python setup.py install`. The `focal_cpp` would be compiled to a so file, which you can import directly. It will be generated automatically after compiling.

Sorry that I have no idea whether this would be compatible with version before 1.6. Maybe some api will not be recognised. You could have a try to see if it can work. Or if you do not mind speed and memory usage, you can use operators written with pure pytorch, which in theory will be better supported.

**Comment by CoinCheung** [comment]
Simply close this, since the question is answered, and no more question comes out.

**Comment by eagle20111** [comment]
Hi, 
 when I running the script: python setup.py install. some erros come.  How can I do it ?

/home/liu/anaconda3/lib/python3.8/site-packages/torch/include/ATen/core/builtin_function.h(117): warning #20236-D: pragma "diag_default" is deprecated, use "nv_diag_default" instead

csrc/common.hpp(107): error: function template "THCCeilDiv" has already been defined

csrc/common.hpp(116): error: function template "THCRoundUp" has already been defined

2 errors detected in the compilation of "csrc/focal_kernel.cu".
error: command '/usr/local/cuda-11.6/bin/nvcc' failed with exit code 1

**Comment by dreamlychina** [comment]
> Hi, when I running the script: python setup.py install. some erros come. How can I do it ?
> 
> /home/liu/anaconda3/lib/python3.8/site-packages/torch/include/ATen/core/builtin_function.h(117): warning #20236-D: pragma "diag_default" is deprecated, use "nv_diag_default" instead
> 
> csrc/common.hpp(107): error: function template "THCCeilDiv" has already been defined
> 
> csrc/common.hpp(116): error: function template "THCRoundUp" has already been defined
> 
> 2 errors detected in the compilation of "csrc/focal_kernel.cu". error: command '/usr/local/cuda-11.6/bin/nvcc' failed with exit code 1

+1
