### ISSUE TITLE
some question in rankloss

### ISSUE THREAD

**Issue by nijiazhi** [CoinCheung/pytorch-loss#35]
hi, do you have any work and plans in rankloss?

No one seems to provide the listwise loss.

**Comment by cemamxiaoxixi** [comment]
您的邮件我已经收到，会尽快回复的。

**Comment by CoinCheung** [comment]
To be honest, I am not familiar with this field. What do you mean by listwise loss ? Like [this paper](https://arxiv.org/pdf/2004.01113.pdf)?

**Comment by nijiazhi** [comment]
thx for reply. 

I mean the rank task in pytorch, like this https://wildltr.github.io/ptranking/

**Comment by CoinCheung** [comment]
> hi, do you have any work and plans in rankloss?
> 
> No one seems to provide the listwise loss.

Thanks for telling me what is listwise loss. I am sure I do not have such work and plan until now. I will leave this open, and see whether other people can help you.

**Comment by nijiazhi** [comment]
OK，thx a lot :)
