### ISSUE TITLE
关于triplet loss

### ISSUE THREAD

**Issue by AnnaXiong** [CoinCheung/pytorch-loss#9]
您好，我有个关于triplet loss求梯度的问题（虽然pytorch是自动求导的），我看网上是用损失分别对anchor、positive、negtive的嵌入向量求偏导，但从您的损失函数中看不出来

**Comment by CoinCheung** [comment]
triplet-loss我用的也是pytorch的自动求导呀，没自己写backward。。。。

**Comment by AnnaXiong** [comment]
@CoinCheung 前段时间我刚接触pytorch，现在好像整明白了

**Comment by CoinCheung** [comment]
嗷那我先把这个关了啊
